export const premiumTheme = {
  primary: "#5A1F3D",
  primaryHover: "#46172F",
  secondary: "#C8A96A",
  success: "#167A5A",
  warning: "#D8A938",
  danger: "#B42318",
  background: "#F7F4EF",
  card: "#FFFEFA",
  border: "rgba(28,28,30,.105)",
  text: "#1C1C1E",
  muted: "#6F6A64",
  softPrimary: "rgba(90,31,61,.09)",
  softSecondary: "rgba(200,169,106,.16)",
  radius: "22px",
};

export const premiumLabels = {
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    allProducts: "كل المنتجات",
    about: "من نحن",
    contact: "تواصل معنا",
    wishlist: "المفضلة",
    cart: "السلة",
    checkout: "إتمام الطلب",
    account: "حسابي",
    login: "دخول العميل",
    register: "إنشاء حساب",
    search: "ابحث عن منتج...",
    shopNow: "تسوق الآن",
    viewProducts: "عرض المنتجات",
    addToCart: "أضف للسلة",
    addedToCart: "تمت الإضافة للسلة",
    quickView: "تفاصيل المنتج",
    outOfStock: "غير متوفر",
    inStock: "متوفر",
    newArrival: "وصل حديثًا",
    sale: "خصم",
    bestSeller: "الأكثر مبيعًا",
    featured: "منتجات مميزة",
    latest: "وصل حديثًا",
    offers: "العروض",
    categories: "التصنيفات",
    brands: "البراندات",
    reviews: "آراء العملاء",
    services: "خدمات المتجر",
    blog: "المدونة",
    instagram: "معرض إنستجرام",
    empty: "لا توجد بيانات متاحة حاليًا",
    newsletterTitle: "انضم لقائمة العروض",
    newsletterText: "استقبل أحدث المنتجات والعروض مباشرة من المتجر.",
    subscribe: "اشترك الآن",
    loadingTitle: "جاري تجهيز تجربة التسوق",
    loadingText: "نحمّل بيانات المتجر والمنتجات بأفضل شكل.",
    subtotal: "الإجمالي الفرعي",
    shipping: "الشحن",
    tax: "الضريبة",
    total: "الإجمالي",
    continueShopping: "متابعة التسوق",
    placeOrder: "تأكيد الطلب",
    customerInfo: "بيانات العميل",
    orderSummary: "ملخص الطلب",
    paymentMethods: "طرق الدفع",
    shippingPolicy: "سياسة الشحن",
    returnPolicy: "سياسة الاسترجاع",
    terms: "الشروط والأحكام",
    powered: "يعمل بواسطة MIZAR",
  },
  en: {
    home: "Home",
    products: "Products",
    allProducts: "All products",
    about: "About",
    contact: "Contact",
    wishlist: "Wishlist",
    cart: "Cart",
    checkout: "Checkout",
    account: "Account",
    login: "Customer login",
    register: "Create account",
    search: "Search products...",
    shopNow: "Shop now",
    viewProducts: "View products",
    addToCart: "Add to cart",
    addedToCart: "Added to cart",
    quickView: "Product details",
    outOfStock: "Out of stock",
    inStock: "In stock",
    newArrival: "New arrival",
    sale: "Sale",
    bestSeller: "Best seller",
    featured: "Featured products",
    latest: "New arrivals",
    offers: "Offers",
    categories: "Categories",
    brands: "Brands",
    reviews: "Customer reviews",
    services: "Store services",
    blog: "Blog",
    instagram: "Instagram gallery",
    empty: "No data available yet",
    newsletterTitle: "Join the offers list",
    newsletterText: "Get latest products and offers directly from the store.",
    subscribe: "Subscribe",
    loadingTitle: "Preparing shopping experience",
    loadingText: "Loading store data and products in the best layout.",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax",
    total: "Total",
    continueShopping: "Continue shopping",
    placeOrder: "Place order",
    customerInfo: "Customer information",
    orderSummary: "Order summary",
    paymentMethods: "Payment methods",
    shippingPolicy: "Shipping policy",
    returnPolicy: "Return policy",
    terms: "Terms and conditions",
    powered: "Powered by MIZAR",
  },
} as const;
