export const theme = {
  key: "BAZAAR_CARDS",
  name: "Bazaar Cards",
  primary: "#F97316",
  primaryHover: "#EA580C",
  secondary: "#16A34A",
  success: "#16A34A",
  warning: "#FACC15",
  danger: "#D32F2F",
  background: "#FFFDF5",
  card: "#FFFFFF",
  border: "#FED7AA",
  text: "#172554",
  muted: "#64748B",
  softPrimary: "rgba(249,115,22,.10)",
  softSecondary: "rgba(22,163,74,.10)",
  radius: "16px",
};

export const bazaarCardsLabels = {
  ar: {
    styleName: "بازار كاردز",
    mood: "قالب سريع للمنتجات والتصنيفات الكثيرة",
    home: "الرئيسية",
    products: "المنتجات",
    allProducts: "كل المنتجات",
    categories: "التصنيفات",
    about: "من نحن",
    contact: "تواصل معنا",
    account: "حسابي",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    cart: "السلة",
    checkout: "إتمام الطلب",
    wishlist: "المفضلة",
    search: "ابحث عن منتج...",
    shopNow: "تسوق الآن",
    viewProducts: "عرض المنتجات",
    continueShopping: "متابعة التسوق",
    addToCart: "أضف للسلة",
    addedToCart: "تمت الإضافة للسلة",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    sale: "خصم",
    featured: "منتجات مميزة",
    bestSeller: "الأكثر مبيعًا",
    latest: "وصل حديثًا",
    offers: "العروض",
    services: "خدماتنا",
    brands: "العلامات التجارية",
    reviews: "آراء العملاء",
    blog: "المدونة",
    instagram: "إنستجرام",
    newsletterTitle: "اشترك في النشرة البريدية",
    newsletterText: "تابع أحدث المنتجات والعروض من المتجر.",
    loadingTitle: "جاري تجهيز المتجر...",
    loadingText: "لحظات ونفتح لك تجربة التسوق.",
    customerInfo: "بيانات العميل",
    placeOrder: "تأكيد الطلب",
    orderSummary: "ملخص الطلب",
    subtotal: "المجموع الفرعي",
    shipping: "الشحن",
    tax: "الضريبة",
    total: "الإجمالي",
    shippingPolicy: "سياسة الشحن",
    returnPolicy: "سياسة الاسترجاع",
    terms: "الشروط والأحكام",
    powered: "Powered by MIZAR",
  },
  en: {
    styleName: "Bazaar Cards",
    mood: "Fast template for rich categories and local commerce",
    home: "Home",
    products: "Products",
    allProducts: "All products",
    categories: "Categories",
    about: "About",
    contact: "Contact",
    account: "Account",
    login: "Login",
    register: "Register",
    cart: "Cart",
    checkout: "Checkout",
    wishlist: "Wishlist",
    search: "Search products...",
    shopNow: "Shop now",
    viewProducts: "View products",
    continueShopping: "Continue shopping",
    addToCart: "Add to cart",
    addedToCart: "Added to cart",
    inStock: "In stock",
    outOfStock: "Out of stock",
    sale: "Sale",
    featured: "Featured",
    bestSeller: "Best sellers",
    latest: "New arrivals",
    offers: "Offers",
    services: "Services",
    brands: "Brands",
    reviews: "Reviews",
    blog: "Blog",
    instagram: "Instagram",
    newsletterTitle: "Join our newsletter",
    newsletterText: "Get the latest products and offers from the store.",
    loadingTitle: "Preparing the store...",
    loadingText: "Just a moment while we open the shopping experience.",
    customerInfo: "Customer information",
    placeOrder: "Place order",
    orderSummary: "Order summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    tax: "Tax",
    total: "Total",
    shippingPolicy: "Shipping policy",
    returnPolicy: "Return policy",
    terms: "Terms and conditions",
    powered: "Powered by MIZAR",
  },
} as const;

export const bazaarCardsTheme = theme;

// Backward-compatible export because Bazaar Cards reuses helpers copied from Mizar Premium.
// This keeps existing imports working while the template has its own Bazaar labels.
export const premiumLabels = bazaarCardsLabels;
