-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "productDiscountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "shippingFeeSnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "subtotalAfterDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "subtotalBeforeDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN     "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "discountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "finalPrice" DOUBLE PRECISION,
ADD COLUMN     "finalTotal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "originalPrice" DOUBLE PRECISION,
ADD COLUMN     "originalTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX "Order_createdAt_idx" ON "Order"("createdAt");
